CREATE TABLE  IF NOT EXISTS TABLE_PROJECT_CUSTOMER_2(
  id          INTEGER PRIMARY KEY,
  description VARCHAR(64) NOT NULL,
  completed   BIT NOT NULL);
  
  
  ALTER TABLE TABLE_PROJECT_CUSTOMER_2 
CHARACTER SET utf8 
COLLATE utf8mb3_general_ci;