CREATE TABLE IF NOT EXISTS TABLE_PROJECT_CUSTOMER_1 ( 
    EventId INT AUTO_INCREMENT NOT NULL, 
    EventName VARCHAR(255),
    EventName2 VARCHAR(255),
    PRIMARY KEY (EventId)
    );
    
    
ALTER TABLE TABLE_PROJECT_CUSTOMER_1 
CHARACTER SET utf8 
COLLATE utf8mb3_general_ci;