package com.baont8.toolgenerate.repository.projectCustomer.query;

public class CmMessageQuery {

	public static final String FIND_CM_MESSAGE = 
			    " with t1 as ( "
			  + "  select t1.MSG_GRP, t1.MSG_CD, t1.COMP_CD, t1.MSG_TYPE , t1.SYS_CD, t1.CAT_TYPE  "
			  + "  from cm_message t1 "
			  + "  where t1.USE_FLAG = 'Y'  "
			  + "  and  "
			  + " 	(  "
			  + " 		t1.MSG is not null  "
			  + " 		and  "
			  + " 		TRIM(upper(t1.MSG))  = TRIM(upper(:MSG))  "
			  + " 	) "
			  + "  and (t1.LANG_CD is not null and t1.LANG_CD in ('KO', 'EN'))  "
			  + "), "
			  + "t2 as ( "
			  + "	select t2.* "
			  + "	from cm_message t2 "
			  + "	inner join t1 "
			  + "	  on t1.MSG_GRP = t2.MSG_GRP  "
			  + "	 and t1.MSG_CD = t2.MSG_CD  "
			  + "	 and t1.COMP_CD = t2.COMP_CD  "
			  + "	 and t1.MSG_TYPE = t2.MSG_TYPE  "
			  + "	 and t1.SYS_CD = t2.SYS_CD  "
			  + "	 and t1.CAT_TYPE = t2.CAT_TYPE "
			  + "	where (t2.LANG_CD is not null and t2.LANG_CD in ('KO', 'EN'))  "
			  + "	 and t2.USE_FLAG = 'Y'  "
			  + "), "
			  + "t3 as ( "
			  + "	select t2.MSG_GRP, t2.MSG_CD, t2.COMP_CD, t2.MSG_TYPE , t2.SYS_CD, t2.CAT_TYPE,			 "
			  + "	  		 MAX( "
			  + "	  		 	case  "
			  + "	  		 		when t2.LANG_CD = 'KO' then t2.MSG  else null  "
			  + "	  		 	end "
			  + "	  		 ) as MSG_KO, "
			  + "	  		 MAX( "
			  + "	  		 	case  "
			  + "	  		 		when t2.LANG_CD = 'EN' then t2.MSG else null  "
			  + "	  		 	end "
			  + "	  		 ) as MSG_EN "
			  + "	from t2 "
			  + "	  group by MSG_GRP, MSG_CD, COMP_CD, MSG_TYPE , SYS_CD, CAT_TYPE "
			  + "	  order by   "
			  + "	 	  case   "
			  + "	 		  when t2.MSG_TYPE = 'LBL' then 1  "
			  + "	 		  when t2.MSG_TYPE = 'BTN' then 2  "
			  + "	 		  when t2.MSG_TYPE = 'MSG' then 3  "
			  + "	 		  when t2.MSG_TYPE = 'TAB' then 4  "
			  + "	 		  when t2.MSG_TYPE = 'FAC' then 5  "
			  + "	 		  else 6  "
			  + "	 	  end asc,  "
			  + "	 	  case  "
			  + "	 		  when t2.COMP_CD = '*' then 1  "
			  + "	 		  when t2.COMP_CD = 'LG01' then 2  "
			  + "	 		  else 3  "
			  + "	 	  end asc,  "
			  + "	 	  case  "
			  + "	 		  when t2.SYS_CD = 'HR' then 1  "
			  + "	 		  else 2  "
			  + "	 	  end asc  "
			  + "	 "
			  + ") "
			  + "select t3.MSG_GRP, t3.MSG_CD, t3.COMP_CD, t3.MSG_TYPE, t3.SYS_CD, t3.CAT_TYPE, t3.MSG_KO, t3.MSG_EN "
			  + "from t3 ";
}
