USE toolGenerate;

ALTER DATABASE toolGenerate CHARACTER SET='utf8mb3'  COLLATE='utf8mb3_bin';

CREATE TABLE  IF NOT EXISTS `file_template` (
  `FILE_TEMPLATE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `FILE_CONTENT` longtext DEFAULT NULL,
  `FILE_CONTENT_FORMAT` longtext DEFAULT NULL,
  `FILE_DESCRIPTION` longtext DEFAULT NULL,
  `FILE_TEMPLATE_EXTENSION` varchar(255) DEFAULT NULL,
  `FILE_TEMPLATE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`FILE_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;


CREATE TABLE  IF NOT EXISTS `group_data` (
  `GROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `GROUP_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;


CREATE TABLE  IF NOT EXISTS `relationship_file_parameter` (
  `FILE_TEMPLATE_PARAMETER_ID` int(11) NOT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `RELATIONSHIP_FILE_PARAMETER_ID` int(11) NOT NULL,
  `RELATIONSHIP_FILE_TEMPLATE_ID` int(11) NOT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `PATTERN_VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`FILE_TEMPLATE_PARAMETER_ID`,`GROUP_ID`,`RELATIONSHIP_FILE_PARAMETER_ID`,`RELATIONSHIP_FILE_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;


CREATE TABLE  IF NOT EXISTS `file_template_parameter` (
  `FILE_TEMPLATE_PARAMETER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `BELONG_TO_THE_BLOCK` varchar(255) DEFAULT NULL,
  `PARAMETER_DEFAULT_VALUE` longtext DEFAULT NULL,
  `PARAMETER_DESCRIPTION` varchar(255) DEFAULT NULL,
  `PARAMETER_KEY` varchar(255) DEFAULT NULL,
  `PARAMETER_REQUIRED` bit(1) DEFAULT NULL,
  `PARAMETER_TYPE` enum('BLOCK','PARAM') DEFAULT NULL,
  `FILE_TEMPLATE_ID` int(11) NOT NULL,
  PRIMARY KEY (`FILE_TEMPLATE_PARAMETER_ID`),
  KEY `FKmf5w7gme848rc6n3ipdd2vi44` (`FILE_TEMPLATE_ID`),
  CONSTRAINT `FKmf5w7gme848rc6n3ipdd2vi44` FOREIGN KEY (`FILE_TEMPLATE_ID`) REFERENCES `file_template` (`FILE_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

ALTER TABLE `file_template_parameter` ADD COLUMN IF NOT EXISTS `IS_OPEN` bit(1) DEFAULT 1;

CREATE TABLE  IF NOT EXISTS `group_file_template` (
  `FILE_TEMPLATE_ID` int(11) NOT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`FILE_TEMPLATE_ID`,`GROUP_ID`),
  KEY `FK7r9eus66g983wmnax1lb0ww65` (`GROUP_ID`),
  CONSTRAINT `FK7r9eus66g983wmnax1lb0ww65` FOREIGN KEY (`GROUP_ID`) REFERENCES `group_data` (`GROUP_ID`),
  CONSTRAINT `FKcfe98dpw5tb5j30kvvfodfi8p` FOREIGN KEY (`FILE_TEMPLATE_ID`) REFERENCES `file_template` (`FILE_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- toolgenerate.document_storage definition

CREATE TABLE IF NOT EXISTS `document_storage` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `EXTENSION` varchar(255) NOT NULL,
  `NAME` varchar(2000) NOT NULL,
  `ORIGINAL_NAME` varchar(2000) NOT NULL,
  `PATH` varchar(2000) NOT NULL,
  `SIZE` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;


CREATE TABLE IF NOT EXISTS `file_template_document_storage` (
  `DOCUMENT_STORAGE_ID` bigint(20) NOT NULL,
  `FILE_TEMPLATE_ID` int(11) NOT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_STORAGE_ID`,`FILE_TEMPLATE_ID`),
  KEY `FKdhecja8o01pps09h4e788ce4q` (`FILE_TEMPLATE_ID`),
  CONSTRAINT `FK95et57vhkmw31xjvtrgfje4y2` FOREIGN KEY (`DOCUMENT_STORAGE_ID`) REFERENCES `document_storage` (`ID`),
  CONSTRAINT `FKdhecja8o01pps09h4e788ce4q` FOREIGN KEY (`FILE_TEMPLATE_ID`) REFERENCES `file_template` (`FILE_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

CREATE TABLE IF NOT EXISTS `revinfo` (
  `REV` int(11) NOT NULL AUTO_INCREMENT,
  `REVTSTMP` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`REV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

CREATE TABLE IF NOT EXISTS `file_template_aud` (
  `FILE_TEMPLATE_ID` int(11) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `FILE_CONTENT` longtext DEFAULT NULL,
  `FILE_CONTENT_FORMAT` longtext DEFAULT NULL,
  `FILE_DESCRIPTION` longtext DEFAULT NULL,
  `FILE_TEMPLATE_EXTENSION` varchar(255) DEFAULT NULL,
  `FILE_TEMPLATE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REV`,`FILE_TEMPLATE_ID`),
  CONSTRAINT `FK3udmvq5au718uv49y7it4vywn` FOREIGN KEY (`REV`) REFERENCES `revinfo` (`REV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

CREATE TABLE IF NOT EXISTS `file_template_parameter_aud` (
  `FILE_TEMPLATE_PARAMETER_ID` int(11) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `BELONG_TO_THE_BLOCK` varchar(255) DEFAULT NULL,
  `IS_OPEN` bit(1) DEFAULT NULL,
  `PARAMETER_DEFAULT_VALUE` longtext DEFAULT NULL,
  `PARAMETER_DESCRIPTION` varchar(255) DEFAULT NULL,
  `PARAMETER_KEY` varchar(255) DEFAULT NULL,
  `PARAMETER_REQUIRED` bit(1) DEFAULT NULL,
  `PARAMETER_TYPE` enum('BLOCK','PARAM') DEFAULT NULL,
  `FILE_TEMPLATE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REV`,`FILE_TEMPLATE_PARAMETER_ID`),
  CONSTRAINT `FKmyp0ik2ci1m8pj7a11t8yrkm0` FOREIGN KEY (`REV`) REFERENCES `revinfo` (`REV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

CREATE TABLE IF NOT EXISTS `file_template_document_storage_aud` (
  `DOCUMENT_STORAGE_ID` bigint(20) NOT NULL,
  `FILE_TEMPLATE_ID` int(11) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`REV`,`DOCUMENT_STORAGE_ID`,`FILE_TEMPLATE_ID`),
  CONSTRAINT `FKay9uy62v6p7qsy55t1wrc4t3c` FOREIGN KEY (`REV`) REFERENCES `revinfo` (`REV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

ALTER TABLE `file_template` ADD IF NOT EXISTS `IS_FILE_SYSTEM` bit(1) DEFAULT b'0';
ALTER TABLE `file_template_aud` ADD IF NOT EXISTS `IS_FILE_SYSTEM` bit(1) DEFAULT b'0';

-- toolgenerate.setting definition

CREATE TABLE IF NOT EXISTS `setting` (
  `CODE` enum('FILE_TEMPLATE_TO_CREATE_CM_MESSAGE_FOR_HR_CORE','FILE_TEMPLATE_TO_CREATE_CM_MESSAGE_FOR_NEXTHR_CORE') NOT NULL,
  `CRT_DT` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT 'USING',
  `UPDT_DT` datetime(6) DEFAULT NULL,
  `VALUE` tinytext NOT NULL,
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

